/**
* This file was automatically generated by @cosmwasm/ts-codegen@0.16.5.
* DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
* and run the @cosmwasm/ts-codegen generate command to regenerate this file.
*/

export interface AskCountResponse {
  count: number;
}
export type Uint128 = string;
export type Addr = string;
export interface AskCreatedHooksResponse {
  ask: Ask;
}
export interface Ask {
  height: number;
  id: number;
  renewal_fund: Uint128;
  seller: Addr;
  token_id: string;
  [k: string]: unknown;
}
export interface AskHooksResponse {
  hooks: string[];
  [k: string]: unknown;
}
export interface AskOffset {
  price: Uint128;
  token_id: string;
}
export interface AskResponse {
  ask?: Ask | null;
}
export interface AsksBySellerResponse {
  asks: Ask[];
}
export interface AsksResponse {
  asks: Ask[];
}
export interface AsksSortedByPriceResponse {
  asks: Ask[];
}
export interface BidHooksResponse {
  hooks: string[];
  [k: string]: unknown;
}
export interface BidOffset {
  bidder: Addr;
  price: Uint128;
  token_id: string;
}
export interface BidResponse {
  bid?: Bid | null;
}
export interface Bid {
  amount: Uint128;
  bidder: Addr;
  height: number;
  token_id: string;
  [k: string]: unknown;
}
export interface BidsByBidderResponse {
  bids: Bid[];
}
export interface BidsByBidderSortedByExpirationResponse {
  bids: Bid[];
}
export interface BidsResponse {
  bids: Bid[];
}
export interface BidsSortedByPriceResponse {
  bids: Bid[];
}
export interface CollectionBidsByBidderResponse {
  bids: Bid[];
}
export interface CollectionBidsByBidderSortedByExpirationResponse {
  bids: Bid[];
}
export interface CollectionBidsSortedByPriceResponse {
  bids: Bid[];
}
export type ExecuteMsg = {
  set_ask: {
    seller: string;
    token_id: string;
  };
} | {
  update_ask: {
    seller: string;
    token_id: string;
  };
} | {
  set_bid: {
    token_id: string;
  };
} | {
  remove_bid: {
    token_id: string;
  };
} | {
  accept_bid: {
    bidder: string;
    token_id: string;
  };
} | {
  fund_renewal: {
    token_id: string;
  };
} | {
  refund_renewal: {
    token_id: string;
  };
} | {
  process_renewals: {
    height: number;
  };
} | {
  setup: {
    collection: string;
    minter: string;
  };
};
export interface InstantiateMsg {
  blocks_per_year: number;
  min_price: Uint128;
  trading_fee_bps: number;
}
export type MarketplaceContract = Addr;
export type Decimal = string;
export interface ParamsResponse {
  params: SudoParams;
}
export interface SudoParams {
  blocks_per_year: number;
  min_price: Uint128;
  trading_fee_percent: Decimal;
  [k: string]: unknown;
}
export type QueryMsg = {
  ask: {
    token_id: string;
  };
} | {
  asks: {
    limit?: number | null;
    start_after?: number | null;
  };
} | {
  reverse_asks: {
    limit?: number | null;
    start_before?: number | null;
  };
} | {
  ask_count: {};
} | {
  asks_by_seller: {
    limit?: number | null;
    seller: string;
    start_after?: string | null;
  };
} | {
  bid: {
    bidder: string;
    token_id: string;
  };
} | {
  bids_by_bidder: {
    bidder: string;
    limit?: number | null;
    start_after?: string | null;
  };
} | {
  bids: {
    limit?: number | null;
    start_after?: string | null;
    token_id: string;
  };
} | {
  bids_sorted_by_price: {
    limit?: number | null;
    start_after?: BidOffset | null;
  };
} | {
  reverse_bids_sorted_by_price: {
    limit?: number | null;
    start_before?: BidOffset | null;
  };
} | {
  ask_hooks: {};
} | {
  bid_hooks: {};
} | {
  sale_hooks: {};
} | {
  params: {};
} | {
  renewal_queue: {
    height: number;
  };
} | {
  config: {};
};
export interface ReverseAsksSortedByPriceResponse {
  asks: Ask[];
}
export interface ReverseBidsSortedByPriceResponse {
  bids: Bid[];
}
export interface ReverseCollectionBidsSortedByPriceResponse {
  bids: Bid[];
}
export interface SaleHooksResponse {
  buyer: string;
  seller: string;
  token_id: string;
}
export type SudoMsg = {
  update_params: {
    blocks_per_year?: number | null;
    min_price?: Uint128 | null;
    trading_fee_bps?: number | null;
  };
} | {
  update_name_minter: {
    minter: string;
  };
} | {
  update_name_collection: {
    collection: string;
  };
} | {
  add_ask_hook: {
    hook: string;
  };
} | {
  remove_ask_hook: {
    hook: string;
  };
} | {
  add_bid_hook: {
    hook: string;
  };
} | {
  remove_bid_hook: {
    hook: string;
  };
} | {
  add_sale_hook: {
    hook: string;
  };
} | {
  remove_sale_hook: {
    hook: string;
  };
};