/**
* This file was automatically generated by @cosmwasm/ts-codegen@0.19.0.
* DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
* and run the @cosmwasm/ts-codegen generate command to regenerate this file.
*/

export interface ConfigResponse {
  collection_addr: string;
}
export type ExecuteMsg = {
  update_admin: {
    admin?: string | null;
  };
} | {
  update_whitelist: {
    whitelist?: string | null;
  };
} | {
  mint_and_list: {
    name: string;
  };
};
export type Uint128 = string;
export interface InstantiateMsg {
  admin?: string | null;
  base_price: Uint128;
  collection_code_id: number;
  marketplace_addr: string;
  max_name_length: number;
  min_name_length: number;
}
export type QueryMsg = {
  admin: {};
} | {
  config: {};
} | {
  params: {};
};