/**
* This file was automatically generated by @cosmwasm/ts-codegen@0.19.0.
* DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
* and run the @cosmwasm/ts-codegen generate command to regenerate this file.
*/

export type Uint128 = string;
export interface InstantiateMsg {
  admin?: string | null;
  base_price: Uint128;
  collection_code_id: number;
  marketplace_addr: string;
  max_name_length: number;
  min_name_length: number;
  whitelists: string[];
}
export type ExecuteMsg = {
  mint_and_list: {
    name: string;
  };
} | {
  update_admin: {
    admin?: string | null;
  };
} | {
  pause: {
    pause: boolean;
  };
} | {
  add_whitelist: {
    address: string;
  };
} | {
  remove_whitelist: {
    address: string;
  };
};
export type QueryMsg = {
  admin: {};
} | {
  whitelists: {};
} | {
  collection: {};
} | {
  params: {};
};
export interface AdminResponse {
  admin?: string | null;
}
export interface CollectionResponse {
  collection: string;
}
export interface ParamsResponse {
  base_price: Uint128;
  max_name_length: number;
  min_name_length: number;
}
export type Addr = string;
export interface WhitelistsResponse {
  whitelists: Addr[];
}