/**
* This file was automatically generated by @cosmwasm/ts-codegen@0.19.0.
* DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
* and run the @cosmwasm/ts-codegen generate command to regenerate this file.
*/

export type Expiration = {
  at_height: number;
} | {
  at_time: Timestamp;
} | {
  never: {};
};
export type Timestamp = Uint64;
export type Uint64 = string;
export type Addr = string;
export interface AllNftInfoResponse {
  access: OwnerOfResponse;
  info: NftInfoResponseForMetadataForEmpty;
}
export interface OwnerOfResponse {
  approvals: Approval[];
  owner: string;
}
export interface Approval {
  expires: Expiration;
  spender: string;
}
export interface NftInfoResponseForMetadataForEmpty {
  extension: MetadataForEmpty;
  token_uri?: string | null;
}
export interface MetadataForEmpty {
  bio?: string | null;
  extension: Empty;
  profile?: NFT | null;
  records: TextRecord[];
}
export interface Empty {
  [k: string]: unknown;
}
export interface NFT {
  collection: Addr;
  token_id: string;
}
export interface TextRecord {
  name: string;
  value: string;
  verified_at?: Timestamp | null;
}
export interface AllOperatorsResponse {
  operators: Approval[];
}
export interface AllTokensResponse {
  tokens: string[];
}
export interface ApprovalResponse {
  approval: Approval;
}
export interface ApprovalsResponse {
  approvals: Approval[];
}
export type Decimal = string;
export interface CollectionInfoResponse {
  creator: string;
  description: string;
  explicit_content: boolean;
  external_link?: string | null;
  image: string;
  royalty_info?: RoyaltyInfoResponse | null;
  trading_start_time?: Timestamp | null;
}
export interface RoyaltyInfoResponse {
  payment_address: string;
  share: Decimal;
}
export interface ContractInfoResponse {
  name: string;
  symbol: string;
}
export type ExecuteMsg = "freeze_collection_info" | {
  set_name_marketplace: {
    address: string;
  };
} | {
  update_bio: {
    bio?: string | null;
    name: string;
  };
} | {
  update_profile: {
    name: string;
    profile?: NFT | null;
  };
} | {
  add_text_record: {
    name: string;
    record: TextRecord;
  };
} | {
  remove_text_record: {
    name: string;
    record_name: string;
  };
} | {
  update_text_record: {
    name: string;
    record: TextRecord;
  };
} | {
  transfer_nft: {
    recipient: string;
    token_id: string;
  };
} | {
  send_nft: {
    contract: string;
    msg: Binary;
    token_id: string;
  };
} | {
  approve: {
    expires?: Expiration | null;
    spender: string;
    token_id: string;
  };
} | {
  revoke: {
    spender: string;
    token_id: string;
  };
} | {
  approve_all: {
    expires?: Expiration | null;
    operator: string;
  };
} | {
  revoke_all: {
    operator: string;
  };
} | {
  mint: MintMsgForMetadataForEmpty;
} | {
  burn: {
    token_id: string;
  };
} | {
  update_collection_info: {
    collection_info: UpdateCollectionInfoMsgForRoyaltyInfoResponse;
  };
} | {
  update_trading_start_time: Timestamp | null;
};
export type Binary = string;
export interface MintMsgForMetadataForEmpty {
  extension: MetadataForEmpty;
  owner: string;
  token_id: string;
  token_uri?: string | null;
}
export interface UpdateCollectionInfoMsgForRoyaltyInfoResponse {
  description?: string | null;
  explicit_content?: boolean | null;
  external_link?: string | null;
  image?: string | null;
  royalty_info?: (RoyaltyInfoResponse | null) | null;
}
export interface InstantiateMsg {
  collection_info: CollectionInfoForRoyaltyInfoResponse;
  minter: string;
  name: string;
  symbol: string;
}
export interface CollectionInfoForRoyaltyInfoResponse {
  creator: string;
  description: string;
  explicit_content: boolean;
  external_link?: string | null;
  image: string;
  royalty_info?: RoyaltyInfoResponse | null;
  trading_start_time?: Timestamp | null;
}
export interface MinterResponse {
  minter: string;
}
export interface NftInfoResponse {
  extension: MetadataForEmpty;
  token_uri?: string | null;
}
export interface NumTokensResponse {
  count: number;
}
export interface OperatorsResponse {
  operators: Approval[];
}
export type QueryMsg = {
  name_marketplace: {};
} | {
  bio: {
    name: string;
  };
} | {
  profile: {
    name: string;
  };
} | {
  text_records: {
    name: string;
  };
} | {
  owner_of: {
    include_expired?: boolean | null;
    token_id: string;
  };
} | {
  approval: {
    include_expired?: boolean | null;
    spender: string;
    token_id: string;
  };
} | {
  approvals: {
    include_expired?: boolean | null;
    token_id: string;
  };
} | {
  all_operators: {
    include_expired?: boolean | null;
    limit?: number | null;
    owner: string;
    start_after?: string | null;
  };
} | {
  num_tokens: {};
} | {
  contract_info: {};
} | {
  nft_info: {
    token_id: string;
  };
} | {
  all_nft_info: {
    include_expired?: boolean | null;
    token_id: string;
  };
} | {
  tokens: {
    limit?: number | null;
    owner: string;
    start_after?: string | null;
  };
} | {
  all_tokens: {
    limit?: number | null;
    start_after?: string | null;
  };
} | {
  minter: {};
} | {
  collection_info: {};
};
export interface TokensResponse {
  tokens: string[];
}