/**
* This file was automatically generated by @cosmwasm/ts-codegen@0.16.5.
* DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
* and run the @cosmwasm/ts-codegen generate command to regenerate this file.
*/

import { Coin } from "@cosmjs/amino";
import { MsgExecuteContractEncodeObject } from "cosmwasm";
import { MsgExecuteContract } from "cosmjs-types/cosmwasm/wasm/v1/tx";
import { toUtf8 } from "@cosmjs/encoding";
import { CountResponse, ExecuteMsg, InstantiateMsg, QueryMsg, Addr, State } from "./Sg721Name.types";
export interface Sg721NameMessage {
  contractAddress: string;
  sender: string;
  increment: (funds?: Coin[]) => MsgExecuteContractEncodeObject;
  reset: ({
    count
  }: {
    count: number;
  }, funds?: Coin[]) => MsgExecuteContractEncodeObject;
}
export class Sg721NameMessageComposer implements Sg721NameMessage {
  sender: string;
  contractAddress: string;

  constructor(sender: string, contractAddress: string) {
    this.sender = sender;
    this.contractAddress = contractAddress;
    this.increment = this.increment.bind(this);
    this.reset = this.reset.bind(this);
  }

  increment = (funds?: Coin[]): MsgExecuteContractEncodeObject => {
    return {
      typeUrl: "/cosmwasm.wasm.v1.MsgExecuteContract",
      value: MsgExecuteContract.fromPartial({
        sender: this.sender,
        contract: this.contractAddress,
        msg: toUtf8(JSON.stringify({
          increment: {}
        })),
        funds
      })
    };
  };
  reset = ({
    count
  }: {
    count: number;
  }, funds?: Coin[]): MsgExecuteContractEncodeObject => {
    return {
      typeUrl: "/cosmwasm.wasm.v1.MsgExecuteContract",
      value: MsgExecuteContract.fromPartial({
        sender: this.sender,
        contract: this.contractAddress,
        msg: toUtf8(JSON.stringify({
          reset: {
            count
          }
        })),
        funds
      })
    };
  };
}