/**
* This file was automatically generated by @cosmwasm/ts-codegen@0.19.0.
* DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
* and run the @cosmwasm/ts-codegen generate command to regenerate this file.
*/

export type Decimal = string;
export type Timestamp = Uint64;
export type Uint64 = string;
export interface InstantiateMsg {
  collection_info: CollectionInfoForRoyaltyInfoResponse;
  minter: string;
  name: string;
  symbol: string;
}
export interface CollectionInfoForRoyaltyInfoResponse {
  creator: string;
  description: string;
  explicit_content?: boolean | null;
  external_link?: string | null;
  image: string;
  royalty_info?: RoyaltyInfoResponse | null;
  start_trading_time?: Timestamp | null;
}
export interface RoyaltyInfoResponse {
  payment_address: string;
  share: Decimal;
}
export type ExecuteMsg = {
  set_name_marketplace: {
    address: string;
  };
} | {
  associate_address: {
    address?: string | null;
    name: string;
  };
} | {
  update_metadata: {
    metadata?: Metadata | null;
    name: string;
  };
} | {
  update_image_nft: {
    name: string;
    nft?: NFT | null;
  };
} | {
  add_text_record: {
    name: string;
    record: TextRecord;
  };
} | {
  remove_text_record: {
    name: string;
    record_name: string;
  };
} | {
  update_text_record: {
    name: string;
    record: TextRecord;
  };
} | {
  verify_text_record: {
    name: string;
    record_name: string;
    result: boolean;
  };
} | {
  update_verifier: {
    verifier?: string | null;
  };
} | {
  transfer_nft: {
    recipient: string;
    token_id: string;
  };
} | {
  send_nft: {
    contract: string;
    msg: Binary;
    token_id: string;
  };
} | {
  approve: {
    expires?: Expiration | null;
    spender: string;
    token_id: string;
  };
} | {
  revoke: {
    spender: string;
    token_id: string;
  };
} | {
  approve_all: {
    expires?: Expiration | null;
    operator: string;
  };
} | {
  revoke_all: {
    operator: string;
  };
} | {
  mint: MintMsgForMetadata;
} | {
  burn: {
    token_id: string;
  };
} | {
  update_collection_info: {
    collection_info: UpdateCollectionInfoMsgForRoyaltyInfoResponse;
  };
} | {
  update_start_trading_time: Timestamp | null;
} | {
  freeze_collection_info: {};
};
export type Addr = string;
export type Binary = string;
export type Expiration = {
  at_height: number;
} | {
  at_time: Timestamp;
} | {
  never: {};
};
export interface Metadata {
  image_nft?: NFT | null;
  records: TextRecord[];
}
export interface NFT {
  collection: Addr;
  token_id: string;
}
export interface TextRecord {
  name: string;
  value: string;
  verified?: boolean | null;
}
export interface MintMsgForMetadata {
  extension: Metadata;
  owner: string;
  token_id: string;
  token_uri?: string | null;
}
export interface UpdateCollectionInfoMsgForRoyaltyInfoResponse {
  description?: string | null;
  explicit_content?: boolean | null;
  external_link?: string | null;
  image?: string | null;
  royalty_info?: (RoyaltyInfoResponse | null) | null;
}
export type QueryMsg = {
  params: {};
} | {
  name: {
    address: string;
  };
} | {
  name_marketplace: {};
} | {
  verifier: {};
} | {
  owner_of: {
    include_expired?: boolean | null;
    token_id: string;
  };
} | {
  approval: {
    include_expired?: boolean | null;
    spender: string;
    token_id: string;
  };
} | {
  approvals: {
    include_expired?: boolean | null;
    token_id: string;
  };
} | {
  all_operators: {
    include_expired?: boolean | null;
    limit?: number | null;
    owner: string;
    start_after?: string | null;
  };
} | {
  num_tokens: {};
} | {
  contract_info: {};
} | {
  nft_info: {
    token_id: string;
  };
} | {
  all_nft_info: {
    include_expired?: boolean | null;
    token_id: string;
  };
} | {
  tokens: {
    limit?: number | null;
    owner: string;
    start_after?: string | null;
  };
} | {
  all_tokens: {
    limit?: number | null;
    start_after?: string | null;
  };
} | {
  minter: {};
} | {
  collection_info: {};
};
export interface AllNftInfoResponseForMetadata {
  access: OwnerOfResponse;
  info: NftInfoResponseForMetadata;
}
export interface OwnerOfResponse {
  approvals: Approval[];
  owner: string;
}
export interface Approval {
  expires: Expiration;
  spender: string;
}
export interface NftInfoResponseForMetadata {
  extension: Metadata;
  token_uri?: string | null;
}
export interface OperatorsResponse {
  operators: Approval[];
}
export interface TokensResponse {
  tokens: string[];
}
export interface ApprovalResponse {
  approval: Approval;
}
export interface ApprovalsResponse {
  approvals: Approval[];
}
export interface CollectionInfoResponse {
  creator: string;
  description: string;
  explicit_content?: boolean | null;
  external_link?: string | null;
  image: string;
  royalty_info?: RoyaltyInfoResponse | null;
  start_trading_time?: Timestamp | null;
}
export interface ContractInfoResponse {
  name: string;
  symbol: string;
}
export interface MinterResponse {
  minter: string;
}
export interface NameResponse {
  name: string;
}
export interface NameMarketplaceResponse {
  address: string;
}
export interface NumTokensResponse {
  count: number;
}
export interface ParamsResponse {
  max_record_count: number;
}
export type Nullable_String = string | null;