/**
* This file was automatically generated by @cosmwasm/ts-codegen@0.35.3.
* DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
* and run the @cosmwasm/ts-codegen generate command to regenerate this file.
*/

export interface InstantiateMsg {
  addresses: string[];
  admin_list?: string[] | null;
  mint_discount_amount?: number | null;
  per_address_limit: number;
}
export type ExecuteMsg = {
  update_admins: {
    new_admin_list: string[];
  };
} | {
  add_addresses: {
    addresses: string[];
  };
} | {
  remove_addresses: {
    addresses: string[];
  };
} | {
  process_address: {
    address: string;
  };
} | {
  update_per_address_limit: {
    limit: number;
  };
} | {
  purge: {};
};
export type QueryMsg = {
  config: {};
} | {
  includes_address: {
    address: string;
  };
} | {
  mint_count: {
    address: string;
  };
} | {
  is_processable: {
    address: string;
  };
} | {
  admins: {};
} | {
  address_count: {};
} | {
  per_address_limit: {};
} | {
  mint_discount_amount: {};
};
export type Uint64 = number;
export interface AdminResponse {
  admin?: string | null;
}
export type Addr = string;
export interface Config {
  admins: Addr[];
  mint_discount_amount?: number | null;
  per_address_limit: number;
}
export type Boolean = boolean;
export type Nullableuint64 = number | null;